### PR TITLE
Update InfoPlist.strings for the Ukrainian translation

### PR DESCRIPTION
**Pull request by rbolgaryn**
### First time contributor checklist

- [x] I have read the [README](https://github.com/WhisperSystems/Signal-iOS/blob/master/README.md) and [CONTRIBUTING](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md) documents
- [ ] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [x] My commits are rebased on the latest master branch
- [x] My commits are in nice logical chunks
- [x] My contribution is fully baked and is ready to be merged as is
- [ ] I have tested my contribution on these devices:
 * iDevice A, iOS X.Y.Z
 * iDevice B, iOS Z.Y

- - - - - - - - - -

### CODE REVIEW

**Comment by Xashyar** [comment]
Hello @rbolgaryn,
GitHub is not used for merging translations, PTAL:

https://github.com/signalapp/Signal-iOS#contributing-translations

**Comment by rbolgaryn** [comment]
> 
> 
> Hello @rbolgaryn,
> GitHub is not used for merging translations, PTAL:
> 
> https://github.com/signalapp/Signal-iOS#contributing-translations

Okay, thank you

**Comment by rbolgaryn** [comment]
Reopened because I could not find a way to edit Ukrainian strings through Transifex (somehow the dialog does not let you choose Ukrainian).

**Comment by DariusVil** [comment]
> Reopened because I could not find a way to edit Ukrainian strings through Transifex (somehow the dialog does not let you choose Ukrainian).

It does for me.
Screenshot 2021-02-26 at 15 30 49

**Comment by rbolgaryn** [comment]
Thanks I'll try again

**Pull request closed without merging**
