### PR TITLE
Capitalization & Punctuation Errors Fixed (English)

### PR DESCRIPTION
**Pull request by BedirEkim**
### First Time Contributor Checklist
- [x] I have read the [README](https://github.com/signalapp/Signal-iOS/blob/main/README.md) and [CONTRIBUTING](https://github.com/signalapp/Signal-iOS/blob/main/CONTRIBUTING.md) documents.
- [x] I have signed the [Contributor Licence Agreement](https://signal.org/cla/).

### Contributor Checklist
- [x] My commits are rebased on the latest main branch.
- [x] My commits are in nice logical chunks.
- [x] My contribution is fully baked and is ready to be merged as is.
- [x] I have tested my contribution on these devices:
 * iPhone 14 Pro, iOS 16.5
 * iPhone 7, iOS 15.7.5

- - - - - - - - - -

### Description
I fixed typos I encountered while using Signal that were visually disturbing.

### CODE REVIEW

**Comment by BedirEkim** [comment]
Example: Unanswered voice call -> Unanswered Voice Call
Screenshot

**Comment by louisgrasset** [comment]
I never saw English was supposed to use capitalization everywhere. Thus, not sure that's something we are expecting in Signal

**Comment by Miguel-Signal** [comment]
@louisgrasset This is by design on iOS, as Apple encourages you to use title case. Please see https://developer.apple.com/design/human-interface-guidelines/alerts

**Comment by louisgrasset** [comment]
Oh then forget about my comment! I wasn't aware, thanks for sharing that with me 🙉

**Pull request closed without merging**
