### PR TITLE
Fix a Polish translation typo

### PR DESCRIPTION
**Pull request by jstasiak**
### First time contributor checklist

- [x] I have read the [README](https://github.com/WhisperSystems/Signal-iOS/blob/master/README.md) and [CONTRIBUTING](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md) documents
- [ ] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [x] My commits are rebased on the latest master branch
- [x] My commits are in nice logical chunks
- [x] My contribution is fully baked and is ready to be merged as is
- [ ] I have tested my contribution on these devices:
 * n/a

### CODE REVIEW

**Comment by Imperiopolis-Signal** [comment]
Hi @jstasiak thanks for your contribution. We can't modify translations directly via github, because they will be overwritten next time we pull the latest translations. If you want to correct a translation, you can do so via [transifex](https://www.transifex.com/signalapp/signal-ios/).

**Comment by jstasiak** [comment]
Hey, I don't have time for that but feel free to migrate this patch wherever makes more sense.

**Comment by riyapenn-signal** [comment]
This string doesn't seem to be listed in Transifex. Do you see this string live in the app?

**Comment by jstasiak** [comment]
I've seen it live in the app running on another person's phone some time ago.

**Comment by rbolgaryn** [comment]
I believe I have a similar problem - I could not translate Ukrainian strings through transifex, that was supported in the dialog.

**Pull request closed without merging**
