### PR TITLE
Improve Mac Catalyst build

### PR DESCRIPTION
**Pull request by saagarjha**
### First time contributor checklist

- [X] I have read the [README](https://github.com/signalapp/Signal-iOS/blob/main/README.md) and [CONTRIBUTING](https://github.com/signalapp/Signal-iOS/blob/main/CONTRIBUTING.md) documents
- [X] I have signed the [Contributor Licence Agreement](https://signal.org/cla/)

### Contributor checklist

- [X] My commits are rebased on the latest main branch
- [X] My commits are in nice logical chunks
- [X] My contribution is fully baked and is ready to be merged as is
- [X] I have tested my contribution on these devices:
 * MacBook Pro (14-inch, 2021) running macOS Ventura 13.2 (22D49)

- - - - - - - - - -

### Description

I tried building Signal for Mac Catalyst. It doesn't quite build out of the box, due to availability issues, but without these changes it doesn't even include all the right targets. Also, the build instructions were out of date so I updated those.

### CODE REVIEW

**Comment by EvanHahn-Signal** [comment]
Thanks for this.

We don't plan to support Mac Catalyst, so I don't think we'll take d54029c502ab1580c4fa5664fa1cc12e96408818.

However, 3af69a4ce04962e3ed4d9164cfbce923ecdfd3d5 looks good to me. I'll manually merge it soon. The next time we push to this repository, that commit should be included. Thanks!

I'm going to close this, but know that part of it has been (manually) merged.

**Comment by saagarjha** [comment]
I will note that all the other targets have Catalyst build support enabled. I understand that you don't plan on supporting or shipping this, but does it need to be explicitly disabled for one component?

**Comment by electr1fy0** [comment]
>We don't plan to support Mac Catalyst

Do you plan to continue with the super heavy electron app forever?
Even Whatsapp has their native app now.

**Comment by exihuatl** [comment]
Can we restart this discussion? Mac Catalyst seems like a better alternative than Electron for Mac users.

**Comment by trbutler** [comment]
Yes, please revisit this. A Catalyst app would be vastly superior to the current Electron app. Or just allow the current iPad app to be run from the App Store on MacOS, at least.

**Comment by singhalrishi27** [comment]
> >We don't plan to support Mac Catalyst
> 
> 
> 
> Do you plan to continue with the super heavy electron app forever?
> 
> Even Whatsapp has their native app now.
> 
> 
> 
> 
> 
> 

Yeah can't believe they are refusing for community support why so much arrogance

**Comment by patjolata** [comment]
>Or just allow the current iPad app to be run from the App Store on MacOS, at least.

That would be nice start for the beginning. The Mac App Store would warn you that the app is not tested for Mac, but it would be very nice.

**Comment by trbutler** [comment]
I wish there were. The iPad app is really good and, if nothing else, I just wish they'd allow it to be installed on a Mac (unmodified even). Even if it weren't the officially promoted option, it'd be a great alternative for those of us who want notifications without keeping the app open all the time, prefer not to have a whole additional instance of Chromium running in the background, etc.). That'd be better than nothing...

**Comment by singhalrishi27** [comment]
> I wish there were. The iPad app is really good and, if nothing else, I just wish they'd allow it to be installed on a Mac (unmodified even). Even if it weren't the officially promoted option, it'd be a great alternative for those of us who want notifications without keeping the app open all the time, prefer not to have a whole additional instance of Chromium running in the background, etc.). That'd be better than nothing...

who are you asking? Most arrogant developers in the world. It feels like north korea here lol.

**Comment by fknfilewalker** [comment]
@saagarjha Please reopen this.

**Comment by saagarjha** [comment]
I don’t really think there is much more for me to add here, unfortunately. If you’d like to build on these changes you can grab them from the diff?

**Comment by fknfilewalker** [comment]
@saagarjha why is it not possible to make signal a universal app with the same app running on iOS iPadOS and macOS.

**Comment by saagarjha** [comment]
I'm not sure why you are asking me this

**Comment by fknfilewalker** [comment]
Aah sorry, I wanted to link @EvanHahn-Signal

**Pull request closed without merging**
