### PR TITLE
Fix #3844: Incorrect voice messages duration

### LINKED ISSUE #3844: Incorrect voice messages duration
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When a voice message is received, it is shown that the length is (let’s say) 14 seconds, instead the audio will reproduce for 17 seconds.

### Steps to reproduce
- receive a voice message
- click play to reproduce
- wait until it reaches the “end”, but it goes on for 3/4 seconds more

**Actual result:** voice message is longer than expected

**Expected result:** voice message length should be the exact duration of the audio

### Screenshots
45a1a027-0004-49db-9595-8ce07a100bfa

### Device info

**Device**: iPhone 8 Plus

**iOS version**: 11.4

**Signal version:** 2.29.0.16 beta

### Link to debug log

https://debuglogs.org/56a3b60e3fce2dbdf310b822c27c98bf95c50748b54b9e46efabd977f1950f20.zip

### PR DESCRIPTION
**Pull request by purpleplatypus**
… by telling AVAudioPlayer that we REALLY, seriously intend to play this file

### First time contributor checklist

- [x] I have read the [README](https://github.com/WhisperSystems/Signal-iOS/blob/master/README.md) and [CONTRIBUTING](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md) documents
- [x] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)

### Contributor checklist

_This section was deleted, so sure, I'm following a blank check?_
- [?] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [x] My commits are rebased on the latest master branch
- [x] My commits are in nice logical chunks
- [x] My contribution is fully baked and is ready to be merged as is
- [x] I have tested my contribution on these devices:
 * iPhone 6, iOS 12.0.1

- - - - - - - - - -

### Description

Fixes #3844 and related #3086. Tested by sending test audio file to iPhone 6 running debug version of this with fixes, and then sending same file to iPhone SE running Signal 2.20.2.16. See #3844 for instructions and test audio.

### CODE REVIEW

**Comment by purpleplatypus** [comment]
Here's a screenshot of the fixed behavior.
img_0001

**Comment by purpleplatypus** [comment]
PTAL @michaelkirk

**Comment by purpleplatypus** [comment]
Thanks for checking. Did you install the build first and then send yourself
the test audio message? Computation of the duration is only being done upon
receipt and then cached; even with these changes, previously received
messages still will have the wrong duration.

Also, could I get the iOS version you tested on?

**Comment by purpleplatypus** [comment]
I think that should do it for the historical fix, PTAL @michaelkirk.

**Comment by tzs1** [comment]
I wish this could be merged soon! 😄

**Comment by purpleplatypus** [comment]
@michaelkirk-signal Any more feedback on this?

**Comment by tzs1** [comment]
Bug still happening. Version 2.37.0.9 beta

**Comment by thegesuser** [comment]
Same here. Still incorrect voice message length 
In the iOS App
Signal Desktop

**Comment by Imperiopolis-Signal** [comment]
Thanks so much for your contribution! I've pulled your changes into our internal fork, expect to see them turn up in the 2.41 release branch soon.

**Pull request closed without merging**
