### PR TITLE
Add App Store trademark credit line

### PR DESCRIPTION
**Pull request by malekhr**
### First time contributor checklist

- [x] I have read the [README](https://github.com/WhisperSystems/Signal-iOS/blob/master/README.md) and [CONTRIBUTING](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md) documents
- [x] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [x] My commits are rebased on the latest master branch
- [x] My commits are in nice logical chunks
- [x] My contribution is fully baked and is ready to be merged as is
- [x] I have tested my contribution on these devices:
 * not applicable
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in my commit message

- - - - - - - - - -

### Description

Adds the App Store credit line as required by Apple: https://developer.apple.com/app-store/marketing/guidelines/#legal

### CODE REVIEW

**Comment by armata** [comment]
PTAL: @michaelkirk

**Comment by armata** [comment]
@michaelkirk this should be ready to merge

**Comment by armata** [comment]
PTAL: @michaelkirk

**Comment by armata** [comment]
PTAL: @michaelkirk

**Comment by michaelkirk** [comment]
Hey @armata, I'm aware this PR is open - no need for continued pinging.

**Pull request closed without merging**
