### PR TITLE
return to path of selected video

### PR DESCRIPTION
**Pull request by KVTaniguchi**
### First time contributor checklist

- [ x] I have read the [README](https://github.com/WhisperSystems/Signal-iOS/blob/master/README.md) and [CONTRIBUTING](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md) documents
- [x ] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [ x] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [ x] My commits are rebased on the latest master branch
- [x ] My commits are in nice logical chunks
- [x ] My contribution is fully baked and is ready to be merged as is
- [x] I have tested my contribution on these devices:
 * iPhone 7, iOS 10.1
 * iPhone 6.3, iOS 9.3
- [x ] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in my commit message

- - - - - - - - - -

### Description

The purpose of this PR is to fix [Issue 1293](https://github.com/WhisperSystems/Signal-iOS/issues/1293) where a user tapping on a video message for viewing in a long message stream is not returned to that selected cell when the video is closed. 

I tested that this fix works by creating long message streams with video messages in the middle, clicking on the video, pausing and closing, letting the video run and closing, and observing that the collection view scrolled to the path of the selected video.

### CODE REVIEW

**Comment by michaelkirk** [comment]
So, it looks like this code has us scrolling back to wherever we came from before the movie was presented. 

From  a UX standpoint, it would be much better to just *not* scroll to the end of the thread when a movie is presented.  I also suspect that approach would create cleaner code than catching a notification to undo something that shouldn't have happened in the first place.

**Comment by KVTaniguchi** [comment]
@michaelkirk, sounds good, will do

**Comment by KVTaniguchi** [comment]
@michaelkirk updated by using ```JSQMessagesViewController``` ```automaticallyScrollsToMostRecentMessage``` property.

**Comment by KVTaniguchi** [comment]
updated

**Comment by michaelkirk-signal** [comment]
This behavior has since been addressed.

**Pull request closed without merging**
