### PR TITLE
Fix conversation view insets.

### PR DESCRIPTION
**Pull request by charlesmchen-signal**
Fixes: First message(s) in new, mostly-empty conversations hidden under the conversation view's navigation header. 

PTAL @michaelkirk

### CODE REVIEW

**Comment by charlesmchen-signal** [comment]
@michaelkirk I pushed another commit because I realized that this also can affects our table views in some cases (see `applyScrollViewInsetsFix`).

**Comment by JasTySYmKeq93EaCPhWxNBtHwJh6** [comment]
Any troubleshooting steps you want me to try in the mean time?

**Comment by JasTySYmKeq93EaCPhWxNBtHwJh6** [comment]
Sometimes the conversation will quit crashing such as right now with this person after we get a few messages going.
But I can’t delete the conversation.
It’ll crash when I try to delete it.

**Comment by JasTySYmKeq93EaCPhWxNBtHwJh6** [comment]
https://debuglogs.org/d36551a0feaff06d2bd573f95955bb9a9efcd197170db71d6bdfd064a866c1ca.zip

**Comment by charlesmchen-signal** [comment]
Closing in favor of #3718

**Pull request closed without merging**
