### PR TITLE
Add pinterest domain and asset domains for link preview support

### PR DESCRIPTION
**Pull request by cmswalker**
### First time contributor checklist
- [x] I have read the [README](https://github.com/WhisperSystems/Signal-iOS/blob/master/README.md) and [CONTRIBUTING](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md) documents
- [x] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)

### Contributor checklist
- [x] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [x] My commits are rebased on the latest master branch
- [x] My commits are in nice logical chunks
- [] My contribution is fully baked and is ready to be merged as is
- [] I have tested my contribution on these devices:
 * iDevice A, iOS X.Y.Z
 * iDevice B, iOS Z.Y

- - - - - - - - - -

### Description

We'd like signal to show link previews for Pinterest 😄
Android PR: signalapp/Signal-Android#8760
Desktop PR: https://github.com/signalapp/Signal-Desktop/pull/3308

### CODE REVIEW

**Comment by cmswalker** [comment]
Actually having issues getting this to crawl properly. Is there a user-agent header ios is setting when requesting the metadata that differs from android?

**Comment by charlesmchen-signal** [comment]
@cmswalker I've merged these changes.  They'll appear in the next release.

**Comment by denver-s** [comment]
International versions don't work (pinterest.it, pinterest.es, pinterest.de, etc.).

**Comment by cmswalker** [comment]
Good callouts, I planned on monitoring traffic for .com to start before
expanding the allowed list too much

**Pull request closed without merging**
