### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Cerberus0**
### First time contributor checklist

- [x] I have read the [README](https://github.com/WhisperSystems/Signal-iOS/blob/master/README.md) and [CONTRIBUTING](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md) documents
- [x] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [x] My commits are rebased on the latest master branch
- [x] My commits are in nice logical chunks
- [x] My contribution is fully baked and is ready to be merged as is
- [n/a] I have tested my contribution

- - - - - - - - - -

### Description

Changes "occured" to "occurred".

### CODE REVIEW

**Comment by hkdavid2008** [comment]
The time of the self-destruction, can you add a custom option,so  i can set it to more than 1 week.

**Comment by Cerberus0** [comment]
I'm closing this PR because the issue appears to be fixed in version 3.5.0.10:

https://github.com/signalapp/Signal-iOS/blob/3.5.0.10/Signal/translations/en.lproj/Localizable.strings#L3228

**Comment by u32i64** [comment]
@Cerberus0 Yeah, your merged commit is here: 4160c96.

**Comment by michaelkirk-signal** [comment]
Thanks - indeed, merged in https://github.com/signalapp/Signal-iOS/commit/4160c969fab28b1ec44fe4865deb119ca08cb56b

**Pull request closed without merging**
