### PR TITLE
Add accessible actions to fix #4480

### LINKED ISSUE #4480: accessibility for conversation deletion/archive
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A friend using VO is unable to delete or archive messages.

### Steps to reproduce
- Launch app with existing conversations.
- Attempt to swipe left on a conversation using a VO tool.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
A recent version update changed the movement mechanism for deleting or archiving messages. My friend is unable to use the 'swipe' motion via VO to view the delete/archive options.

Apologies that I do not have access to an iOS device to reproduce & better describe the issue.

### PR DESCRIPTION
**Pull request by VidaHasan**
### First time contributor checklist

- [x] I have read the [README](https://github.com/WhisperSystems/Signal-iOS/blob/master/README.md) and [CONTRIBUTING](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md) documents
- [x] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [x] My commits are rebased on the latest master branch
- [x] My commits are in nice logical chunks
- [x] My contribution is fully baked and is ready to be merged as is
- [x] I have tested my contribution on these devices:
 * iPhone SE simulator (Accessibility Inspector)
 * iPhone XS Max (VoiceOver)

- - - - - - - - - -

### Description

- Addresses #4480 by making our custom archive and delete actions accessible
- Tested by checking available actions on conversation cell and activating them via Accessibility inspector

### CODE REVIEW

**Comment by VidaHasan** [comment]
Unfortunately, I'm not able to understand the clang-format check issue. Can someone share details on how to run locally and find my format error? I also posted about this in the forum.

https://community.signalusers.org/t/checking-clang-format-errors-before-pushing-to-pr/15035

**Comment by Imperiopolis-Signal** [comment]
Hi @VidaHasan thanks for this contribution, these changes are great. Don't worry about the CI for now. One request: can you also add support for the read/unread action? It's a leading action that functions similarly to these two trailing actions.

**Comment by VidaHasan** [comment]
> Hi @VidaHasan thanks for this contribution, these changes are great. Don't worry about the CI for now. One request: can you also add support for the read/unread action? It's a leading action that functions similarly to these two trailing actions.

Yes can do!

**Comment by VidaHasan** [comment]
@Imperiopolis-Signal , added now.

**Comment by VidaHasan** [comment]
@Imperiopolis-Signal , any guidance on fixing the lint issues or do I not need to worry about linting at all for this to merge?

ty

**Comment by Imperiopolis-Signal** [comment]
don’t worry about it

**Comment by Imperiopolis-Signal** [comment]
af27a92c35348b1d6191fb10c88735d737884181

**Pull request closed without merging**
