### PR TITLE
refactor/OWSAddToContactViewController

### PR DESCRIPTION
**Pull request by decanus**
### First time contributor checklist

- [x] I have read the [README](https://github.com/WhisperSystems/Signal-iOS/blob/master/README.md) and [CONTRIBUTING](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md) documents
- [x] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [x] My commits are rebased on the latest master branch
- [x] My commits are in nice logical chunks
- [x] My contribution is fully baked and is ready to be merged as is
- [x] I have tested my contribution on these devices:
 * iOS Simulator iPhone 11

- - - - - - - - - -
This pull request does 2 main things:
 - It refactors the `OWSAddToContactViewController` from `objc` to `swift`
 - We change the tables in the controller to use `ContactCell` similar to the `ContactsPicker`.

I did this because through this change it will be able to easily add Search and Sections similar to the `ContactsPicker`, this has been something I've encountered multiple times that has annoyed me hence I decided to fix.

### CODE REVIEW

**Comment by decanus** [comment]
@Imperiopolis-Signal I can't figure out why the lint part of this doesn't work.

**Comment by Imperiopolis-Signal** [comment]
> @Imperiopolis-Signal I can't figure out why the lint part of this doesn't work.

You can ignore that failure, it's failing because you deleted a file. It'll be fixed soon.

**Comment by decanus** [comment]
Ah okay, I thought it might be that. Thanks @Imperiopolis-Signal

**Comment by decanus** [comment]
hey @Imperiopolis-Signal is there a chance you'd merge this? there's a conflict now cause it hasnt been looked at in a while. If it can get merged I am happy to fix the conflict.

**Comment by Imperiopolis-Signal** [comment]
Yes, it's definitely possible, but in general expect a larger wait before we get a chance to review big PRs like this. We're a small team and the majority of our time is focused on developing new features not looking at public contributions. As long as the PR remains open, we haven't ruled out merging it and we may come back to you with change requests.

**Comment by decanus** [comment]
perfect, then I will update @Imperiopolis-Signal, didn't mean to rush!

**Comment by decanus** [comment]
closing in favour of https://github.com/signalapp/Signal-iOS/pull/4482

**Pull request closed without merging**
