### PR TITLE
Add Share location feature FREEBIE

### PR DESCRIPTION
**Pull request by christophhagen**
Added a new class ShareLocationManager, which integrates with
MessagesViewController to allow sending the current location. The
implementation tries to mimic the existing behaviour on Android.
Permissions for location services are also handled.

### Contributor checklist

- [X] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [X] My commits are rebased on the latest master branch
- [X] My commits are in nice logical chunks
- [X] My contribution is fully baked and is ready to be merged as is
- [X] I have tested my contribution on these devices:
 * iPhone 6, iOS 11.0 (15A5327)
 - [X] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in my commit message

- - - - - - - - - -

### Description

Had messed up my repository a bit, sorry for the repost.

Adds a "share current location" feature to Signal. The behaviour is close to the behaviour already present in Signal-Android. The location coordinates are determined before a google maps static image is created, which is then sent together with a message containing the coordinates, address information and a google maps link.
The feature is accessible through the attachment picker.

## Implementation details
- Location service permissions are handled
- Error messages will be displayed if location could not be sent
- Strings required  are added to Localized.strings
- Description for location use is added to Signal-Info.plist
- CoreLocation framework is added as required dependency
- The ShareLocationManager class handles the whole process
- The size of the static maps image is 400x400 pixels (can easily be changed)
- A self-designed icon is included for the attachment picker

See the screenshots for how it looks from the sending and receiving side.

If anything about the implementation needs to be fixed, please let me know.

## Screenshots

| Attachment picker |  Location permission |
|:--------------------:|:----------------------|
Attachment picker | img_1450
| Sent location |  No permission dialog |
img_1451 | img_1453
| No internet connection | 
img_1452

### CODE REVIEW

**Comment by RiseT** [comment]
FYI: You have to include the word "FREEBIE" in the (I think first) commit message, not in the PR's title. Otherwise this will have no effect.

**Comment by christophhagen** [comment]
Thanks for the info. It worked in the past, but you're right, I'll add it to the commit message next time

**Comment by mattboldt** [comment]
Any updates on this? I see the build is failing but the last contribution was August.

**Comment by christophhagen** [comment]
I pushed this feature two times already, it seems there is currently no interest in including this feature into Signal.

**Comment by pkosiec** [comment]
Hey @charlesmchen @michaelkirk-signal @michaelkirk, can you take a look at this PR? This feature is very useful and it's there for Android users for such a long time. Thanks!

**Comment by rocknjohn** [comment]
I wonder if there are privacy implications of fetching a preview from Google Maps? Would be beneficial to do via a proxy on Signal's server, similar to how GIFs are fetched from Giphy via a proxy?

(Btw, great work here! It's beautiful. Hopefully the devs can spend some time responding to, accepting, or closing some of the open PRs.)

**Comment by jbannister** [comment]
Text => Disappearing Message 💯 
Map => Disappearing Map 👎
Sad!

**Comment by alexander-sibert** [comment]
I miss this feature also. Now other messengers offer additional Live location sharing sometimes useful if you meet friends or contacts.

**Comment by igorkulman** [comment]
It is a shame this never got merged, not even giving any reason why not.

**Comment by Imperiopolis-Signal** [comment]
Hi, thanks so much for your contribution. I'm sorry we didn't get a chance to properly review this. We're open to considering this feature in the future, but since this PR is so old it's not possible to integrate it as is.

Also, as someone mentioned earlier in this thread, there are some privacy implications to the approach used and in general requesting location access. It might be best to wait and utilize iOS 13's "just once" permission model to allow users to only share their location with the app for the moment they're sending this message.

 Feel free to open a new PR based off the latest code and ping me to take a look.

**Pull request closed without merging**
