### PR TITLE
Add selection accessibility trait for selected message

### PR DESCRIPTION
**Pull request by VidaHasan**
### Contributor checklist

- [x] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [x] My commits are rebased on the latest master branch
- [x] My commits are in nice logical chunks
- [x] My contribution is fully baked and is ready to be merged as is
- [x] I have tested my contribution on these devices:
 iOS Simulator with using accessibility inspector

- - - - - - - - - -

### Description
Addresses issue #4809. 

- Builds accessibility traits based message selection status
- This enables VoiceOver users to know which messages are selected

### CODE REVIEW

**Review by ralphstone1 — CHANGES_REQUESTED** [review]
Yes

**Comment by VidaHasan** [comment]
@Imperiopolis-Signal, 

Apologies if pings aren't acceptable.

I'm looking to get this PR merged and it looks like the CI is failing from lint. Can someone share steps I need to take to fix please?

**Comment by ralphstone1** [comment]
Ty

**Comment by VidaHasan** [comment]
now stale. closing

**Pull request closed without merging**
