### PR TITLE
Adds InfoPlist.strings.

### PR DESCRIPTION
**Pull request by fumiakiy**
### First time contributor checklist

- [x] I have read the [README](https://github.com/WhisperSystems/Signal-iOS/blob/master/README.md) and [CONTRIBUTING](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md) documents
- [x] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [x] My commits are rebased on the latest master branch
- [x] My commits are in nice logical chunks
- [x] My contribution is fully baked and is ready to be merged as is
- [x] I have tested my contribution on these devices:
 * iOS Simulator iPhone SE 2nd Gen, iOS 13.4

- - - - - - - - - -

### Description

I noticed that the contents in the permission dialogs were not translated. I added a base (en) file and a translation (Japanese which I am native of). I don't know how it could be picked up by Transifex, so let me know if I need to do something more, for example to add the file to all translation folders.

Screenshots before and after in a device in Japanese:

Before
before

After
after

### CODE REVIEW

**Comment by fumiakiy** [comment]
Should I update submodules too?

**Comment by Imperiopolis-Signal** [comment]
This change was incorporated in db5ccc10d95946aeb29b420360fb6e3f4c70e6be and the InfoPlist.strings have been made available for translation on Transifex. Thank you for your contribution!

**Comment by sg25dev** [comment]
I have logged in to Transifex in an attempt to update the French strings for the InfoPlist.strings but Transifex shows that French is 100% complete however I don't see a localization for French like I do German and Japanese for this file on the master branch.

**Comment by Imperiopolis-Signal** [comment]
> I have logged in to Transifex in an attempt to update the French strings for the InfoPlist.strings but Transifex shows that French is 100% complete however I don't see a localization for French like I do German and Japanese for this file on the master branch.

We pull available translations from transifex before each release. It likely wasn’t translated yet before our last release. It should be in the next release.

**Pull request closed without merging**
