### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rocknjohn**
### Contributor checklist
- [x] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [x] My commits are rebased on the latest master branch
- [x] My commits are in nice logical chunks
- [x] My contribution is fully baked and is ready to be merged as is
- [x] I have tested my contribution on these devices:
 * iDevice A, iOS X.Y.Z
 * iDevice B, iOS Z.Y

- - - - - - - - - -

### Description
Improves README. Goal is to unify branding, improve credibility, and encourage visitors to download and star on github. 

* Adds logo
* Add status badges
* Adds links to Signal Android and Signal Desktop
* Update AppStore button to a non-distorted version and adds required Apple legal text
* Removes Bithub reference because these were removed from Signal Android's README in a recent commit
* Removes the SignalKit section. It lacks any description to describe what it is or would would use it. Removing to clean up and remove confusion. Could be re-added if section is improved.
* Logo font is Questrial from https://fonts.google.com/specimen/Questrial  Open source under Open Font License

Further improvements:
* I would prefer a blue on white SVG logo, but I don't have access to any original design assets. I used the highest quality logo I could find.
* Contributing Code section could probably be cleaned up, but I don't have words for that.

### CODE REVIEW

**Comment by rocknjohn** [comment]
Example screenshot

**Comment by rocknjohn** [comment]
Note the releases badge has a bug, it shows version 2.2 instead of 2.19 or 2.20. I've filed a bug report for that: https://github.com/badges/shields/issues/1355 I suggest just keeping it implemented on the README and letting the shields maintainer fix their badge generation code eventually.

**Comment by rocknjohn** [comment]
I wish we could get the `release` badge to show the current release correctly. The shields badge team looked into it and believe it's due to the Signal-iOS project somehow not using releases and just using tags. I don't know whether they are correct: https://github.com/badges/shields/issues/1355

I can update this badge to show the most recent 'tag' instead, which shows correctly: https://img.shields.io/github/tag/whispersystems/signal-ios.svg tag example Although I think 'release' would be more useful for visitors.

Please let me know if you want any changes in order to merge this. If this works well for Signal-IOS, I'd like to do a similar pull request for Android and Desktop to unify Signal branding.

**Comment by rocknjohn** [comment]
Now with updated Twitter, Github and Travis usernames (signalapp) and the Copyright year to 2018.

This is ready to go. Please let me know if any changes are desired.

**Comment by Imperiopolis-Signal** [comment]
Thanks so much for your contribution! I've pulled your changes into our internal fork, expect to see them turn up in the 2.41 release branch soon. We didn't end up including the top section (with logo) you put together as we'd like to keep our README style consistent across all of our repos. The rest of your updates will be present.

**Pull request closed without merging**
