### PR TITLE
Fixes the issue around cleaning up the share extension 

### PR DESCRIPTION
**Pull request by fumiakiy**
### Contributor checklist

- [x] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [x] My commits are rebased on the latest master branch
- [x] My commits are in nice logical chunks
- [x] My contribution is fully baked and is ready to be merged as is
- [x] I have tested my contribution on these devices:
 * iPhone XR, iOS 12.4
 * iPhone SE 2nd gen, iOS 13.5

- - - - - - - - - -

### Description

This PR attempts to fix an issue found both in iOS 12 and in iOS 13. The symptom is the same between the iOS versions but the cause was different. The first commit fixes the issue in iOS 12 while the second commit is specifically to fix it in iOS 13.

#### iOS 12
1. Open Safari, Map or any app that shares a text
1. Start sharing by tapping the share icon
1. Tap the Share icon
1. Select Signal
1. Select a thread to share the photo
1. On the attachment approval view, tap [Cancel], or tap Send button to send it
1. In the share sheet, select Signal again

**Actual behavior:**

Nothing happens. Behind it, the app context swaps, that ultimately calls the previous instance's `deinit`, that kills the process.

Either canceling or sending at the step 6 yields the same result.

Note that if you tap on [X] at the step 5 above, it behaves as expected.

Also note that if you share images from Photo app or any imaging apps, it behaves as expected too.

**Expected behavior:**

Signal share extension opens again. Behind it, at the tap of [Cancel], the process should exit (by calling `ExitShareExtension`).

#### iOS 13
The steps are the same, and the actual behaviors are also the same for the buggy behaviors.

In addition to those, tapping [X] at the step 5 yields the buggy behavior as described in *Actual behavior* above.

Also in iOS 13, image sharing from Photo app yields the same buggy behavior as described in *Actual behavior* above.

----

The PR _may_ fix the issues reported in #4459 and #4316 , but the description of those issues do not exactly match the steps above.

### CODE REVIEW

**Comment by Imperiopolis-Signal** [comment]
I haven't had a chance to review yet, but I will note that #4316 is a different issue that only effects iPad in landscape.

**Comment by fumiakiy** [comment]
> but I will note that #4316 is a different issue that only effects iPad in landscape.

I was able to reproduce the similar (though not exactly the same) issue described in #4316 in my iPhone. The iPad landscape issue you mentioned is #4435 and #4392 I guess? Those issues are not related to this PR.

**Comment by Imperiopolis-Signal** [comment]
Yep, you're right I meant to flag #4435 and #4392 as the ones that were iPad only, but at least with iOS 14 they happen on phones as well.

**Comment by Imperiopolis-Signal** [comment]
In general the changes here look OK, we'll probably get them incorporated in a future release.

**Comment by fumiakiy** [comment]
The gist of the pull request was implemented in [c073d8e204].

I found that in iOS 14 even `viewWillDisappear` isn't called at least in the simulator, so the issue raised in this PR still persists in iOS 14. But I was not able to find a solution for the issue in iOS 14 and the issue in the previous versions have been fixed by the commit.

Closing.

**Pull request closed without merging**
