### PR TITLE
Delete Main.storyboard

### PR DESCRIPTION
**Pull request by AndrewSB**
Looks like this isn't referenced in any of the targets, so (assuming
it's being compiled in to the finished bundle) it's just bloating the
app size by a couple kb

### First time contributor checklist

- [x] I have read the [README](https://github.com/WhisperSystems/Signal-iOS/blob/master/README.md) and [CONTRIBUTING](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md) documents
- [x] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [x] My commits are rebased on the latest master branch
- [x] My commits are in nice logical chunks
- [x] My contribution is fully baked and is ready to be merged as is
- [x] I have tested my contribution on these devices:
 * iPhone SE (2nd generation), iOS 13.3

### CODE REVIEW

**Comment by AndrewSB** [comment]
Looks like CI failed on `AccountManagerTest.testUpdatePushTokens()`, seems unrelated? Perhaps a flaky test?

**Comment by Imperiopolis-Signal** [comment]
Please sign the Contributor License Agreement in order for us to merge your changes.

**Comment by AndrewSB** [comment]
done

**Comment by Imperiopolis-Signal** [comment]
b5d4a6578a9c0c1e7d14127137e1354702f0012f

**Pull request closed without merging**
