### PR TITLE
Add support for Siri Shortcuts

### PR DESCRIPTION
**Pull request by StefanLobbenmeier**
### First time contributor checklist

- [x] I have read the [README](https://github.com/WhisperSystems/Signal-iOS/blob/master/README.md) and [CONTRIBUTING](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md) documents
- [x] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [ ] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [x] My commits are rebased on the latest master branch
- [x] My commits are in nice logical chunks
- [ ] My contribution is fully baked and is ready to be merged as is
- [x] I have tested my contribution on these devices:
 * iPad Simulator (8th Generation), iOS 14.4

- - - - - - - - - -

### Description

Closes (or at least starts with closing) feature requests like 
- https://community.signalusers.org/t/shortcuts-integration/19109/2
- https://www.reddit.com/r/signal/comments/9go4rf/now_that_ios_12_and_shortcuts_is_out_can_we/ (2 years old by now)
- https://www.reddit.com/r/signal/comments/ks6c7a/ios_shortcut_integration/

A screenshot of what a potential shortcut might look like:
image

Current shortcomings:
- In this version this will open Signal and write the Message. I have not quite figured out how to write the Message in the Background (like it is possible with iMessage).
- It is not possible to select the phone number directly. I was able to select a contact instead, but could not find a way to directly set the phone number from a contact in the Shortcut like it is possible with iMessage and WhatsApp.
- I have not developed for iOS before
- No Check for Empty values / Error handling

I wanted to share this state with you though to get some feedback if this is actually something that would be merged and if I used the correct APIs in the Signal codebase

### CODE REVIEW

**Comment by StefanLobbenmeier** [comment]
> I'm following the code, UI and style conventions
The link is bad, there is no headline "code-conventions", so the link https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions is probably wrong

**Comment by deeps-lab** [comment]
Also it would be better if Signal allows Siri to
Read & Send messages

**Comment by StefanLobbenmeier** [comment]
It looks like Signal is now donating suggestions to Siri, but not in a way that messages can be customised.

Would still be very nice to get some feedback on this by someone on Signal.

**Comment by bzumik1** [comment]
How does it look with this feature?

**Comment by StefanLobbenmeier** [comment]
No idea, I haven’t received any kind of feedback so far. Maybe I have to ping someone from the Signal team?

@Imperiopolis-Signal

**Comment by bzumik1** [comment]
I am still waiting for better shortcuts support.

**Comment by lockieluke** [comment]
Please merge I need this feature so badly why are they so slow at merging prs can we just fork it and make a Signal Community version

**Comment by adhulipa** [comment]
This is a great PR! I'm curious, @StefanLobbenmeier, why did you choose to create a new "SendMessage.intentsdefinition" file instead of supporting a handler for the `INSendMessageIntent` directly? 

Ref: https://developer.apple.com/documentation/sirikit/dispatching_intents_to_handlers
> For example, to handle an [INSendMessageIntent](https://developer.apple.com/documentation/sirikit/insendmessageintent), provide an instance of a type that conforms to the [INSendMessageIntentHandling](https://developer.apple.com/documentation/sirikit/insendmessageintenthandling) protocol

**Comment by StefanLobbenmeier** [comment]
@adhulipa honestly because I am not an iOS developer and was not aware of that INSendMessageIntent unlocks a Siri Shortcut.

I was also wondering how you can make a shortcut that supports selecting an account directly. But I first wanted to get the signal team to look at this before I spend more effort investigating on how this might be implemented. But so far I have been ghosted 😢 

Feel free to open another PR where you improve upon my approach, I hope that they somehow react to yours then.

**Comment by StefanLobbenmeier** [comment]
Telegram also has some Intents like I did here: https://github.com/TelegramMessenger/Telegram-iOS/blob/master/Telegram/SiriIntents/en.lproj/Intents.intentdefinition

But I have not used Telegram before so I am not quite sure what they are

**Comment by StefanLobbenmeier** [comment]
Ok i just installed telegram and it looks like those Siri intents are unrelated to shortcuts. In the shortcuts app only one intention is available:

it says „Send Message“, „Send Message to recipient“, „Show while running“:
A1C42DC7-7BE9-4EF4-B502-D45B7D424A7D

**Comment by StefanLobbenmeier** [comment]
I found this [commit ](https://github.com/TelegramMessenger/Telegram-iOS/commit/e5eda4dd674dfb574c48572b251e1c1d15fecbae) claiming to add Siri Shortcut support, but I think it only enabled donating intents like we have in signal, that open the messaging app so you can type, no parameters.

I think support for parameterized use in Siri Shortcuts was enabled sometime in 2021: https://github.com/TelegramMessenger/Telegram-iOS/issues/190#issuecomment-974632180

**Comment by StefanLobbenmeier** [comment]
I read up some more and I dont see how telegram has declared the Shortcut Support. The references to 

But I found this [commit in another messenger](https://github.com/vector-im/element-ios/pull/4863/files), that looks more like my approach.

**Comment by adhulipa** [comment]
Thanks for the notes @StefanLobbenmeier! Super interesting!  -- I am speculating that it's likely the Signal team hasn't looked at this because of the pending merge-conflicts? Do you know how to fix them? 

Also, I would recommend checking the "My PR is fully baked... " checkbox and taking a second look at the description box and making sure it's all updated and tidy.  Generally, in these types of open source projects I have found that the maintainers are super busy and tend to not respond when something doesn't _look_ ready. 

Of course, I'm not a Signal developer :D -- I'm just sharing my experiences from working on open sources contributions from many years ago :D

**Comment by StefanLobbenmeier** [comment]
Yeah I was mostly looking for feedback before I spent any more time on this. Like I said I am not an iOS developer, I mostly do Java and Kotlin in the Backend at work, so it would be better if someone with real experience in iOS and app development would take a look. But feel free to cherry pick my commits and try a new PR, for me it will be some time until I have more time to look into this.

**Comment by ShadowRoi** [comment]
@harry-signal  Hey please can we get some more info about this? We need some feedback

**Comment by InnovationBuddy** [comment]
Similar to
[https://github.com/signalapp/Signal-iOS/issues/5030](https://github.com/signalapp/Signal-iOS/issues/5030)

**Comment by eizedev** [comment]
> This issue has been closed due to inactivity.

signal developers doesn’t answer or comment issues/pull requests, in this case, for years but the stale bot github action is set to 1 week.
I am still need this functionality :(

**Comment by ITaluone** [comment]
ping

**Comment by vladtsap** [comment]
can we have this feature?

**Pull request closed without merging**
