### PR TITLE
CI: Run on pushes to master and release branches

### PR DESCRIPTION
**Pull request by EwoutH**
### Contributor checklist
- [x] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [x] My commits are rebased on the latest master branch
- [x] My commits are in nice logical chunks
- [x] My contribution is fully baked and is ready to be merged as is
- [x] I have tested my contribution on these devices:
 * _No functional code changes, so not relevant_

- - - - - - - - - -

### Description
This PR modifies the CI configuration to also run on pushes to the master and release branches, so it can be checked that the CI not only passes when a PR is opened but also after that it's merged.

### CODE REVIEW

**Comment by EwoutH** [comment]
We immediately see great example why it's useful to run CI on master (and release) branches: With CI failing it easy to see which commit last passed on the master branch! :)

**Comment by EwoutH** [comment]
@Imperiopolis-Signal It seems you did something change with the force-push of the `signalapp:master` branch.

It's not really common to force-push a master branch, was this a sync of 5.2.0?

**Edit:** Ah, I see you pushed 377 commits to it. I will resolve conflicts in my PR and rebase!

**Comment by EwoutH** [comment]
Rebased and ready to review/merge again!

**Comment by Imperiopolis-Signal** [comment]
The force push was because we wanted to get your FUNDING.yml change merged, but we work on an internal private repo. So I merged it temporarily, then overwrote it when 5.2 was public (which also has your change) so our internal and the external repo are consistent.

**Comment by EwoutH** [comment]
Thanks for the explanation! Having private and public repos is always confusing for outside contributors. (great read by comma.ai: [A 2020 Theme: Externalization](https://medium.com/@comma_ai/a-2020-theme-externalization-13b33326d8b3))

Aside from that, any feedback on this PR?

**Comment by Imperiopolis-Signal** [comment]
> Aside from that, any feedback on this PR?

It seems like a good change. We'll get it merged along with our next release.

**Comment by EwoutH** [comment]
Great! I also found a few ways too shave some seconds from the CI, so I will open a PR for those speedups when this is merged and the CI passes.

And again, thank you for all the amazing work in Signal!

**Comment by EwoutH** [comment]
Rebased and signed commit.

**Comment by EwoutH** [comment]
Rebased and signed commit.

> It seems like a good change. We'll get it merged along with our next release (which also fixes up all the tests)

Anything blocking this PR?

**Comment by EwoutH** [comment]
This has been merged in 24a7dc7, so this can be closed. Thanks!

**Pull request closed without merging**
